# Generated by Django 5.1.4 on 2025-12-31 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="facebook_link",
            field=models.URLField(
                blank=True, help_text="Full Facebook Profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="store_covers/"),
        ),
        migrations.AddField(
            model_name="store",
            name="instagram_link",
            field=models.URLField(
                blank=True, help_text="Full Instagram Profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="payment_account_title",
            field=models.CharField(
                default="Pending Update",
                help_text="Exact name on your account",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="payment_method",
            field=models.CharField(
                choices=[("EP", "Easypaisa"), ("JC", "JazzCash")],
                default="EP",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="payment_number",
            field=models.CharField(default=0, help_text="03XXXXXXXXX", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="marketplace.store",
            ),
        ),
    ]
