# Generated by Django 5.1.4 on 2025-12-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0003_order_quantity_order_total_price_product_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="payment_number",
        ),
        migrations.AddField(
            model_name="store",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EP", "Easypaisa"),
                    ("JC", "JazzCash"),
                    ("SADA", "SadaPay"),
                    ("NAYA", "NayaPay"),
                    ("MEEZAN", "Meezan Bank"),
                    ("HBL", "Habib Bank Limited (HBL)"),
                    ("UBL", "United Bank Limited (UBL)"),
                    ("MCB", "MCB Bank"),
                    ("ABL", "Allied Bank Limited"),
                    ("BAFL", "Bank Alfalah"),
                    ("BAHL", "Bank Al-Habib"),
                    ("FAYSAL", "Faysal Bank"),
                    ("ASKARI", "Askari Bank"),
                    ("SC", "Standard Chartered Bank"),
                    ("HMBL", "Habib Metropolitan Bank"),
                    ("NBP", "National Bank of Pakistan (NBP)"),
                    ("BOP", "Bank of Punjab (BOP)"),
                    ("JS", "JS Bank"),
                    ("SONERI", "Soneri Bank"),
                    ("DIB", "Dubai Islamic Bank"),
                    ("ISLAMI", "BankIslami Pakistan"),
                    ("SINDH", "Sindh Bank"),
                    ("BOK", "Bank of Khyber"),
                    ("SUMMIT", "Summit Bank"),
                    ("SILK", "Silk Bank"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="payment_account_number",
            field=models.CharField(
                blank=True, help_text="Account Number or IBAN", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="facebook_link",
            field=models.URLField(
                blank=True, help_text="Full Facebook Page URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="payment_account_title",
            field=models.CharField(
                blank=True,
                help_text="Exact Title of Account",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery Only"),
                    ("OL", "Online Transfer / Bank Deposit"),
                    ("BOTH", "Both COD and Online Transfer"),
                ],
                default="COD",
                max_length=4,
            ),
        ),
    ]
