# Generated by Django 5.1.4 on 2026-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_is_available_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deliver_nationwide',
            field=models.BooleanField(default=False, verbose_name='Delivers Across Pakistan'),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_cities',
            field=models.TextField(blank=True, help_text='Comma-separated list of other cities', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_account_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
