# Generated by Django 5.1.4 on 2026-01-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_store_deliver_nationwide_store_secondary_cities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Variant Name (e.g. Size)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Details/Chart Info')),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_details/', verbose_name='Size Chart/Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_types', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Value (e.g. Small, Red)')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.productvarianttype')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
