# Generated by Django 5.1.4 on 2026-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_productvarianttype_productvariantitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Delivery Fee (0 for Free)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(default='3-5 Business Days', help_text='e.g., 2-3 Days, Same Day Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Available Stock'),
        ),
    ]
