# Generated by Django 5.1.4 on 2026-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_product_delivery_charges_product_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_charges',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='selected_variant',
            field=models.CharField(blank=True, help_text='e.g. Size: Small', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Variant Old Price'),
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Variant Price (Leave empty to use Base Price)'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Standard Delivery Fee'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_time',
            field=models.CharField(default='3-5 Business Days', help_text='e.g., 2-3 Days, Same Day Delivery', max_length=50),
        ),
    ]
