# Generated by Django 5.1.4 on 2026-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_delivery_fee_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Variant Specific Image'),
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Variant Stock'),
        ),
    ]
