# Generated by Django 5.1.4 on 2026-01-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_productvariantitem_image_productvariantitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Store'),
        ),
        migrations.CreateModel(
            name='StoreVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Legal Name')),
                ('cnic_number', models.CharField(help_text='e.g. 42101-1234567-1', max_length=20, verbose_name='CNIC Number')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Official Email Address')),
                ('office_address', models.TextField(verbose_name='Physical Office/Headquarters Address')),
                ('cnic_front', models.ImageField(upload_to='verification_docs/', verbose_name='CNIC Front Image')),
                ('cnic_back', models.ImageField(upload_to='verification_docs/', verbose_name='CNIC Back Image')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='marketplace.store')),
            ],
        ),
    ]
