# Generated by Django 5.1.4 on 2026-01-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_store_is_verified_storeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the store.', verbose_name='Active/Visible'),
        ),
    ]
