# Generated by Django 5.1.4 on 2026-01-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
