# Generated by Django 5.1.4 on 2026-01-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_order_is_paid_order_safepay_tracker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-is_verified', '-created_at'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # 💎 FIX: Removed 'order_ref' because it already exists in your DB
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('FASHION', 'Fashion & Wearables'), ('TECH', 'Electronics & Gadgets'), ('HOME', 'Home & Lifestyle'), ('BEAUTY', 'Health & Beauty'), ('AUTO', 'Automotive & Parts'), ('FOOD', 'Food & Groceries'), ('OTHER', 'Other / Custom Request')], default='OTHER', max_length=20, verbose_name='Store Category'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Store'),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated for URLs', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storeverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storewallet',
            name='payout_account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storewallet',
            name='payout_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_group_id',
            field=models.CharField(blank=True, help_text='Public Group ID for Cart Checkout', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide product.', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Base Stock'),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Override Price'),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value (e.g. Small)'),
        ),
        migrations.AlterField(
            model_name='productvarianttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvarianttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_details/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Base City'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(verbose_name='About the Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='Store Logo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Badge'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Store Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondary_cities',
            field=models.TextField(blank=True, help_text='Comma-separated list (e.g. Lahore, Islamabad)', null=True),
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FASHION', 'Fashion & Wearables'), ('TECH', 'Electronics & Gadgets'), ('HOME', 'Home & Lifestyle'), ('BEAUTY', 'Health & Beauty'), ('AUTO', 'Automotive & Parts'), ('FOOD', 'Food & Groceries'), ('OTHER', 'Other / Custom Request')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='I am looking for...')),
                ('description', models.TextField(verbose_name='Details (Color, Size, Urgency)')),
                ('reference_image', models.ImageField(upload_to='talash_refs/', verbose_name='Reference Photo')),
                ('budget', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='My Budget (Rs)')),
                ('city', models.CharField(default='Karachi', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]