# Generated by Django 5.1.4 on 2026-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_alter_product_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
